# Matrix Analysis 2022 - EE312
## Week 1  - Background material - Python/Numpy
[N. Aspert](https://people.epfl.ch/nicolas.aspert) - [LTS2](https://lts2.epfl.ch)

The assignments and exercises for this will use Python as a programming language. Python is a general-purpose programming language which is used in various areas. It benefits from an ecosystem of libraries, such as [numpy](https://numpy.org), [scipy](https://scipy.org), [matplotlib](https://matplotlib.org) and many others, which turns it into a powerful tool for scientific computing.

## Objectives
This notebook is meant as an introduction (or a reminder) to Python, Numpy and Matplotlib.

### Notebooks
During this course, we will be using Python through **notebooks**. A notebook allow you to write and execute Python code within your web browser. You can either run the notebook locally on your computer, or using an online service such as [noto](https://noto.epfl.ch) , [binder](https://mybinder.org) or [google colab](https://colab.research.google.com). See the [README](https://github.com/epfl-lts2/matrix-analysis-2022#readme) file in the course Github repository for more details and installation instructions.

You can always call the `help` function within the notebook to access documentation about a particular function/type..., e.g.

In [ ]:
help(complex)

## Python
Python is a very popular dynamically-typed interpreted language. Its design emphasizes readability, by using indentation as code block delimiter, and plain English words (`and`, `or`, ...) instead of the logical operator symbols you may encounter in C or Java : 
```
// in C or Java, indentation is optional (but highly recommended to ensure code remains readable)
int f(int x, int y) {
   if (x == 1 || y > 2) {
     x += 2;
     y = x*3;
  }
  return x*y;
}
```
is written as 
```
# in Python indentation is NOT optional
def f(x, y):
    if x == 1 or y > 2:
        x += 2
        y = x*3
    return x*y
```

### Basic types
Unsurprisingly, Python has a number of base types you can also find in other programming languages, such as integers, floats, strings and booleans, and behave in a similar way. 

#### Numbers

In [ ]:
x = 5
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "5"
print(x + 1)   # Addition; prints "6"
print(x - 1)   # Subtraction; prints "4"
print(x * 2)   # Multiplication; prints "10"
print(x ** 2)  # Exponentiation; prints "25"
x += 1
print(x)  # Prints "6"
x *= 2
print(x)  # Prints "12"
y = 1.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "1.5 2.5 3.0 2.25"

In Python, the `float` type is *double-precision* (i.e. 64-bit), unlike C or Java. Python also benefits from a built-in `complex` type:

In [ ]:
z = 1. + 1.j
print(2*z)     # Prints "2+2j"
print(z**2)    # Prints "2j"
print(type(z)) # Prints "<class 'complex'>"

#### Boolean
Boolean type can have (surprise) two values: `True` or `False` (capital first character matters). Instead of using symbolic operators, Python uses plain English words `and`, `or`, `not`:

In [ ]:
b = True
c = False
print(type(b))     # Prints "<class 'bool'>"
print(b and c)     # Prints "False"
print(b and not c) # Prints "True"

A little care needs to be taken about the `None` value. The `None` keyword is used to define a null value, or no value at all. `None` is not the same as 0, False, or an empty string. 

In [ ]:
n = None
print(type(n))    # Prints "< class 'NoneType'>"

However, logical operators treat `None` in a specific way

In [ ]:
print(n and b)  # Prints "None"
print(not n)    # Prints "True"
print(n or b)   # Prints "True"

#### Strings
Python supports strings

In [ ]:
ma = 'matrix'         # String literals can use single quotes
an = "analysis"       # or double quotes; it does not matter.
print(ma)             # Prints "matrix"
print(len(ma))        # String length; prints "6"
maan = ma + ' ' + an  # String concatenation
print(maan)             # prints "matrix analysis"
maan22 = '{} {} {}'.format(ma, an, 2022) # string formatting
print(maan22)         # prints "matrix analysis 2022"
y0 = 2000
y1 = 22
maan22b = f'{ma} {an} {y0 + y1}' # in python >= 3.6, you can do "string interpolation"
print(maan22b)

`string` has several built-in methods (check the official [documentation](https://docs.python.org/3.9/library/stdtypes.html#string-methods) for more) :

In [ ]:
s = "matrix"
print(s.capitalize())  # Capitalize a string; prints "Matrix"
print(s.upper())       # Convert a string to uppercase; prints "MATRIX"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints " matrix"
print(s.center(8))     # Center a string, padding with spaces; prints " matrix "
print(an.replace('a', '(a)'))  # Replace all instances of one substring with another;
                                # prints "(a)n(a)lysis"
print('  analysis '.strip())  # Strip leading and trailing whitespace; prints "analysis"

### Functions
Python functions are defined using the `def` keyword, e.g.  :

In [ ]:
def f(x, y):
    if x == 1 or y > 2:
        x += 2
        y = x*3
    return x*y

In [ ]:
f(1, 2)

In [ ]:
f(2, 2)

default arguments can be handy

In [ ]:
def f_default(x, y=2):
    return x**y + x

In [ ]:
f_default(3) # equivalent to writing: f_default(3, 2)

It is often the case that functions have a lot of default arguments and you only need to specify a small number of them. You can then use the named argument shortcut:

In [ ]:
def f_long(x, y=1, z=2, h=3, t=None):
    res = x + y - z + h
    if t: # test if t has a value
        res = res*t
    return res

In [ ]:
f_long(12, h=4)

Check the [documentation](https://docs.python.org/3.9/tutorial/controlflow.html#defining-functions) for more details.

#### Control flow
Python supports `if`...`elif`...`else`, `for` loops, `do`...`while`, check the [documentation](https://docs.python.org/3.9/tutorial/controlflow.html#) for more details.

### Data structures
Python has several built-in containers, we will only present the lists and tuples. Check the [documentation](https://docs.python.org/3.9/tutorial/datastructures.html) for more details and other interesting data structures (such as dictionaries or sets).

#### Lists
A Python list is the equivalent of an array, but it can be resized and can mix different types of elements.

In [ ]:
xs = [2, 0, 3]    # Create a list
print(xs, xs[2])  # Prints "[2, 0, 3] 3"
print(xs[-1])     # Negative indices count from the end of the list; prints "3"
xs[2] = 'hello'     # Lists can contain elements of different types
print(xs)         # Prints "[2, 0, 'hello']"
xs.append('world')  # Add a new element to the end of the list
print(xs)         # Prints "[2, 0, 'hello', 'world']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "world [2, 0, 'hello']"

You can not only access individual elements, but also range of elements. This is known as *slicing*

In [ ]:
nums = list(range(8))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4, 6, 7]"
print(nums[3:5])          # Get a slice from index 2 to 4 (exclusive); prints "[3, 4]"
print(nums[4:])           # Get a slice from index 2 to the end; prints "[4, 5, 6, 7]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4, 5, 6, 7]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3, 4, 5, 6]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4, 5, 6, 7]"

You can iterate over a list:

In [ ]:
fruits = ['apple', 'banana', 'pear']
for fruit in fruits:
    print(fruit)
# Prints "apple", "banana", "pear", each on its own line.

*List comprehensions* are a convenient shortcut for list transformation operations :

In [ ]:
nums = list(range(4))
dbl = []
for n in nums:
    dbl.append(n*2)
print(dbl)
# Will print "[0, 2, 4, 6]"

Rewrite the above loop with a list comprehension:

In [ ]:
dbl_c = [n*2 for n in nums]
print(dbl_c) # Prints "[0, 2, 4, 6]"

You can include conditions in list comprehensions:

In [ ]:
dbl_cc = [n*2 for n in nums if n < 2]
print(dbl_cc) # Prints "[0, 2]"

#### Tuples
A tuple is an immutable list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. 

In [ ]:
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(t[0])       # Prints "5"

## Numpy

[Numpy](https://nupy.org) is a core library for scientific computing. It provides optimized routines for multi-dimensional arrays. You can find many online tutorials about Numpy. If you are familiar with Matlab, you may want to check the [Numpy for Matlab users tutorial](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html). As always, check [Numpy documentation](https://numpy.org/doc/stable/user/basics.html) for more information.

### Arrays
Arrays are the base type used by Numpy. Unlike Python lists, they consists in elements having all the same type. They are indexed by non-negative integers, and their elements can also be accessed using square brackets.

You can easily create Numpy arrays from nested lists.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Create a 1D array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)", this is Python's way of displaying a tuple with only one element
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 42                  # Change an element of the array
print(a)                  # Prints "[42, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a 2D array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 2], b[1, 0])   # Prints "1 3 4"

Numpy has helper functions to create arrays:

In [ ]:
a = np.zeros((3,3))   # Create an array of all zeros. You have to pass a tuple as argument 
                      # (beware of the double parentheses)
print(a)              # Prints "[[ 0.  0.  0.]
                      #          [ 0.  0.  0.]
                      #          [ 0.  0.  0.]]"

b = np.ones((1, 3))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.  1.]]"

c = np.full((2,2), 4)  # Create a constant array
print(c)               # Prints "[[ 4.  4.]
                       #          [ 4.  4.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[0.45199657 0.95344055]
                             #               [0.65255911 0.79999078]]"

### Array indexing
We will just review the most important ways of accessing Numpy array elements. Check the [documentation](https://numpy.org/doc/stable/reference/arrays.indexing.html) for details.

You can slice Numpy arrays similarly to lists. 

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array !!
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

# You can use ':' to specify the whole range of a dimension. 
# This prints
# [[ 1 77]
#  [ 5  6]
#  [ 9 10]]
print(a[:, :2])

# When dealing with n-dimensional arrays, the special shortcut '...' stands for 'all remaining dimensions'
c = np.ones((3,2,2)) # create a 3D array
c[1, ...] = c[1, :, :]*2
c[2, ...] = c[2, :, :]*3
# This prints
# [[[1. 1.]
#   [1. 1.]]
#
# [[2. 2.]
#  [2. 2.]]
#
# [[3. 3.]
#  [3. 3.]]]
print(c) 

# This prints
# [[[1., 1.],
#   [1., 1.]]
#
#  [[2., 2.],
#   [2., 2.]]]
print(c[:2, ...])


If you want to avoid modifying the original array when accessing a slice, you need to make a copy of it before writing values.

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = np.array(a) # create a copy of a
c = a[:2, :2]   # create a slice

b[0, 0] = 42 # modify the copy
c[0, 0] = 17 # slice modification
# The following will print :
# [[17  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
# [[42  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
# [[17  2]
#  [ 5  6]]
print(a)
print(b)
print(c)

While slicing produces a sub-array of the original array, **integer array indexing** provides a way to construct an arbitrary array from the original one.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6], [7, 8]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
# the elements a[0, 0], a[2, 1] and a[3, 0]
print(a[[0, 2, 3], 
        [0, 1, 0]])  # Prints "[1 6 7]"

# When using integer array indexing, you can use the same
# element from the source array multiple times:
print(a[[0, 0, 0], [1, 1, 1]])  # Prints "[2 2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1], a[0, 1]]))  # Prints "[2 2 2]"

**Boolean indexing** lets you pick arbitrary elements from an array. This is useful when selecting elements that satisfy some condition.

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6], [7, 8]])

bool_idx = (a > 3) # Returns an numpy array of booleans, having a shape identical to a.
                   # Each element will be True if it satisfies the condition, i.e the corresponding element of a is > 3.

# This prints
# [[False False]
#  [False  True]
#  [ True  True]
#  [ True  True]]
print(bool_idx)

# This will construct a 1D array made of the values of a corresponding to the True values in bool_idx
print(a[bool_idx])  # Prints "[4 5 6 7 8]"

# This can also be done in a single statement:
print(a[a > 3])     # Prints "[4 5 6 7 8]"

### Data types
Numpy arrays' elements, unlike python lists, are all of the same type. Numpy provides [many types](https://numpy.org/doc/stable/reference/arrays.dtypes.html) that can be used to build an array. You can either let Numpy guess the best datatype for your elements, or explicitly specify it.

In [ ]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.float64)   # Force a particular datatype
print(x.dtype)                         # Prints "float64"

### Array operations

You can perform element-wise mathematical operations on Numpy arrays, either using operator overloads or Numpy functions. If you are familiar with Matlab be careful: `*` is the element-wise multiplication in Numpy, and NOT the matrix multiplication (as it is in Matlab) !

Check the [full list of mathematical operations](https://numpy.org/doc/stable/reference/routines.math.html).

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Reshaping an array can be useful, especially through transposition. Transposition can be achieved using the `T` attribute. Numpy also has a `reshape` function.

In [ ]:
x = np.array([[1, 0], [2, -1]])
print(x)     # Prints "[[ 1  0]
             #          [ 2 -1]]"
print(x.T)   # Prints "[[ 1  2]
             #          [ 0 -1]]"

# Be careful with complex matrices, if you want to get the Hermitian transpose, 
# you need to do it explicitely via the H attribute, and not just call .T
z = np.array([[1+1.j, 1.j], [0, -1.j]])
print(z.T)   # Prints "[[ 1.+1.j  0.+0.j]
             #          [ 0.+1.j -0.-1.j]]", i.e. this is just a transposition
print(np.conjugate(z.T))  # Prints "[[ 1.-1.j  0.-0.j]
                          #          [ 0.-2.j -0.+1.j]]"
    
# reshape examples
a = np.arange(0, 6)
print(a)                       # Prints "[0 1 2 3 4 5]"
# reshape the 1D array into a 2D one
print(a.reshape((2,3)))        # Prints "[[0 1 2]
                               #          [3 4 5]]"
# reshape a 2D array into a 1D one
print(x.reshape(4))            # Prints "[ 1  0  2 -1]"
# You can choose if you want to reshape in C (default for Numpy) or Fortran (default for Matlab) layout, 
# i.e. by rows or columns.
print(x.reshape(4, order='F')) # Prints "[ 1  2  0 -1]"

As stated previously, `*` is the element-wise multiplication. If you want to multiply two matrices, you need to call
 `np.matmul` or its shortcut `@` (make sure you checked the course repository's README if you have troubles typing it in Jupyter). `np.dot` computes the inner product between two vectors. It will return the same results as `np.matmul` for matrices (i.e. 2D arrays) but using `np.matmul`or `@` should be preferred.

In [ ]:
a = np.array([[1, 2], [-2, 1]])
b = np.array([[1, 0], [0, -1]])

# This will print 4 times 
# [[ 1 -2]
#  [-2 -1]]
# It will *NOT* work for arrays of dimension greater than 2.
print(np.dot(a, b))
print(np.matmul(a, b))
print(a@b)
print(np.inner(a, b))

There are several ways of computing the inner product $\langle u,v \rangle = u^Tv = \sum_i u_i v_i$, but those equivalences hold only for matrices and (often) not for $N$-dimensional arrays (with $N>2$).

Similarly, you can compute the outer product $uv^T$ using different methods, with the same remarks regarding dimension.

In [ ]:
import numpy as np
u = np.array([1, 1])       # shape = (2,)
uu = np.array([[1], [1]])  # shape = (2,1), we made sure uu would be a column vector, as in the definitions used in the slides.
v = np.array([-1, 0])      # shape = (2,)
vv = np.array([[-1], [0]]) # shape = (2,1)
# Compute the inner product between 2 vectors
# If you want to compute u^T v, you need to resahpe vectors from (2,) to (2,1),
# since here u.T = u and v.T = v
# This prints twice "-1" and once "[[-1]]". Using the matrix multiplication returns an array, instead of a scalar.
print(np.dot(u, v))
print(np.inner(u, v))
print(uu.T@vv)


# If you want to compute u^T.v you need to reshape vectors from (2,) to (2,1) (or use np.outer)
# This prints 3 times
# [[-1  0]
#  [-1  0]]
print(np.dot(uu, vv.T))
print(np.outer(u, v))
print(uu@vv.T)

### Broadcasting

Broadcasting allows to perform arithmetical operations between arrays of different sizes. Of course you need to follow a rule in order to do so: 

"In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one."

In the following example, `x.shape` is `(4, 3)` and `v.shape` is `(3,)`, which fulfills the "equal trailing axis size" condition.

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

Implementing this without broadcasting could be done as:

In [ ]:
y = np.empty_like(x)   # Create an empty matrix with the same shape as x
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

In addition to being more compact notation-wise, broadcasting allows for faster execution time and reduced memory requirements (useful when you work with bigger matrices).

In general, for performance reasons, you should try to avoid using `for` loops and use Numpy functions and broadcasting.

### Exercise

In order to experience that for yourself, fill the function below that will implement "naive" matrix multiplication, using `for` loops (do not use Numpy functions or the `@` operator). Do not forget to check that those matrices can be multiplied together before proceeding with the loops. If you find they are not compatible, you can use the `raise` statement to throw an exception, e.g.
```
def matmul(a, b):
    if <insert test here>:
        raise ValueError('Incompatible sizes')
```


In [ ]:
def matmul(a, b):
    # TODO complete this 
    return None

Make sure those examples are giving the expected results

In [ ]:
a = np.ones((2,2))
b = np.eye(2)
c = np.array([[1, -1, 0], [-1, 0, 1]])
print(matmul(a,b))
print(a@b)
print(matmul(a, c))
print(a@c)
# print(matmul(a, c.T)  # This should generate an exception because of incompatible sizes
# print(a@c.T) # This will generate an exception because of incompatible sizes

Once done, we will check its performance when compared to the Numpy version. Let us generate matrices of suitable size filled with random coefficients (feel free to play with the size to see the impact on performance).

In [ ]:
A1 = np.random.rand(100, 200)
A2 = np.random.rand(200, 100)

In [ ]:
%%timeit
matmul(A1, A2)

The `%%timeit` cell magic will display timing information about the execution of a cell. You can try different matrix sizes to see the impact. In general it is always better to use Numpy native functions (if it is missing, look again in the documentation because it is very likely that you missed it ;) than implementing them yourself. 

In [ ]:
%%timeit
A1@A2

## Matplotlib
[Matplotlib](https://matplotlib.org/) is a library to create plots in Python. It has lots of features, we will therefore only focus on a small subset of them, especially `pyplot` which is a collection of functions that make Matplotlib work like Matlab. Make sure to check the [cheatsheets](https://matplotlib.org/cheatsheets), the [tutorials](https://matplotlib.org/stable/tutorials/index) and of course the [documentation](https://matplotlib.org/stable/api/index.html).

### Basic plots

In [ ]:
import matplotlib.pyplot as plt

# Build some data to be plotted
# x between -2pi and +2pi, sampled with a 0.2 interval
x = np.arange(-2*np.pi, 2*np.pi, 0.2)
y = np.cos(x)

# you can plot directly the 'y' values (python will fill the 'x' values with indices)
plt.plot(y)
plt.show() # can be omitted but avoids extra info to be displayed

In [ ]:
plt.plot(x,y) # if you specify 'x', the x-axis uses those values for display.
plt.show()

It is fairly easy to add legends, axis labels, etc.

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(-2*np.pi, 2*np.pi, 0.2)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

You can style each plot differently (axes, colors, markers, ...). Check the [plot documentation](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot.html) for more.

In [ ]:
plt.plot(x, y_sin, 'r+')
plt.plot(x, y_cos, 'g-')
plt.axis([-10, 10, -2, 2])
plt.show()

### Subplots
A single figure can contain multiple plots thanks to `subplot`



In [ ]:
# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(212) # shortcut notation for plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')
plt.subplots_adjust(top=1.5) # avoid plot legend collision with axis
plt.show()

### Visualizing linear transforms
Let us use Matplotlib to visualize the effect of (simple) linear transforms.
We use `mgrid` to generate the x/y coordinates of a regular lattice.

In [ ]:
c = np.mgrid[-5:6, -5:6]
plt.scatter(c[0], c[1]) # 'scatter' plots point clouds
plt.axis([-10, 10, -10, 10])
plt.grid(visible=True) # show the grid lines
plt.show()

For ease of visualization, our linear transform will be defined by a matrix $A \in \mathbb{R}^{2 \times 2}$ as transformation $\mathbb{R}^2 \rightarrow \mathbb{R}^2$. 

In [ ]:
A = np.array([[2., 0.5], [0, 0.5]])
print(A)

In [ ]:
# coordinates need to be reshaped for matrix multiplication 
coords = np.vstack([c[0].ravel(), c[1].ravel()]) # ravel will flatten a 2D array into a 1D one
print(coords.shape)

In [ ]:
coord_transformed = A@coords

In [ ]:
plt.scatter(c[0], c[1]) # 'scatter' plots point clouds
plt.axis('equal') # display x and y axes with equal steps
plt.scatter(coord_transformed[0, :], coord_transformed[1, :], marker='+', color='r')
plt.grid(visible=True) # show the grid lines
plt.show()

For future use, let us wrap this in a function (you may tweak it according to your needs/preferences)

In [ ]:
# expects an input grid produced via mgrid
def visualize_transform_grid(input_matrix, input_grid):
    coords = np.vstack([input_grid[0].ravel(), input_grid[1].ravel()])
    coords_tr = input_matrix@coords
    plt.scatter(input_grid[0], input_grid[1])
    plt.axis('equal')
    plt.scatter(coords_tr[0, :], coords_tr[1, :], marker='+', color='r')
    plt.grid(visible=True) # show the grid lines
    plt.show()

Let us visualize the effect of a transformation using an "ellipse plot"

In [ ]:
# v1 and v2 are the indices of two unit vectors
def visualize_transform_ellipse(input_matrix, v1=65, v2=100):
    # Creating the vectors for a circle and storing them in x
    xi1 = np.linspace(-1.0, 1.0, 100)
    xi2 = np.linspace(1.0, -1.0, 100)
    yi1 = np.sqrt(1 - xi1**2)
    yi2 = -np.sqrt(1 - xi2**2)

    xi = np.concatenate((xi1, xi2), axis=0)
    yi = np.concatenate((yi1, yi2), axis=0)
    x = np.vstack((xi, yi))

    # getting two samples vector from x
    x_sample1 = x[:, v1]
    x_sample2 = x[:, v2]
    
    # compute the action of A on x
    t = input_matrix @ x
    
    # find transformed sample vectors
    t_sample1 = t[:, v1]
    t_sample2 = t[:, v2]
    
    # plot the result
    f, (ax1, ax2) = plt.subplots(1, 2, sharex=True)
    ax1.plot(x[0,:],x[1,:], color='black')
    ax1.axis('equal')
    ax1.quiver(x_sample1[0], x_sample1[1], angles='xy', scale_units='xy', scale=1, color='b')
    ax1.quiver(x_sample2[0], x_sample2[1], angles='xy', scale_units='xy', scale=1, color='r')
    ax1.grid()

    ax2.plot(t[0,:],t[1,:],color='black')
    ax2.axis('equal')
    ax2.quiver(t_sample1[0], t_sample1[1], angles='xy', scale_units='xy', scale=1, color='b')
    ax2.quiver(t_sample2[0], t_sample2[1], angles='xy', scale_units='xy', scale=1, color='r')
    ax2.grid()

In [ ]:
# change the values of v1 and v2 to see the effect depending on the orientation
visualize_transform_ellipse(A, 75, 100) 

The blue vector gets rotated and stretched but the red horizontal vector is only stretched:
$
A x_2 = \lambda x_2
$
In this example that first eigenvector was easy to spot since reading the columns of the matrix we see that the vector $(1,0)$ is mapped to $(2,0)$, i.e. it is an eigenvector with eigenvalue 2.

### Exercise
Let us study one particular transform, defined by the following matrix:

$$B = \begin{pmatrix} \frac{1}{2} & -\frac{\sqrt{3}}{2} \\ \frac{\sqrt{3}}{2} & \frac{1}{2} \end{pmatrix}$$

What are the properties of this matrix ? What is the effect of this transformation (you can use the visualization functions defined previously) ? 

< Write your answer here >

In [ ]:
B = np.array([[0.5, -0.5*np.sqrt(3)],[0.5*np.sqrt(3), 0.5]])

Compute the matrix of the inverse transformation (without using Numpy's builtin `numpy.linalg.inv`). Hint: remember the properties of $B$.

In [ ]:
B_inv = None # <- replace with your answer

In [ ]:
# verify that you are correct
B@B_inv