# Matrix Analysis 2022 - EE312

## Week 5 - Exercises 
[LTS2](https://lts2.epfl.ch)

1. Let $A = (1,2) \in \mathbb{R}^{1 \times 2}$ show it is onto and compute $A_R^{-1}$.

Let $x=\begin{pmatrix}x_1\\x_2\end{pmatrix}$, $Ax = x_1 + 2x_2$. For any real number $r$, we can use $\begin{pmatrix}r\\0\end{pmatrix}$ as its antecendent via $A$. Therefore any real has an antecedent, meaning $A$ is onto.

$AA_R^{-1} = 1, A_R^{-1}=\begin{pmatrix}1\\0\end{pmatrix}$ or $\begin{pmatrix}3\\-1\end{pmatrix}$ are valid solutions

---

2. Let $A = \begin{pmatrix}1\\2\end{pmatrix} \in \mathbb{R}^{2 \times 1}$ show it is 1-1 and compute $A_L^{-1}$.

Let $x=(x_1, x_2)$ and $y=(y_1, y_2)$, $Ax = \begin{pmatrix}x_1 & x_2\\2x_1 & 2x_2\end{pmatrix}$ and $Ay = \begin{pmatrix}y_1 & y_2\\2y_1 & 2y_2\end{pmatrix}$, clearly $Ax=Ay\Rightarrow x=y$, so $A$ is 1-1. Possible left inverse are the transpose of the ones computed at question 1.

---

3. $AA^+A = A(AA^T)^{-1}A^TA$. Since $AA^T$ is a scalar, it can be moved around, hence $AA^+A = (AA^T)^{-1}AA^TA = A$

$A^+AA^+ = (AA^T)^{-1}A^TA(AA^T)^{-1}A^T = (AA^T)^{-1}A^T (AA^T)^{-1}AA^T = A^+$.

$(AA^+)^T = (A(AA^T)^{-1}A^T)^T = (AA^T)^{-1}(AA^T)^T = (AA^T)^{-1}AA^T = AA^+$.

$(A^+A)^T = ((AA^T)^{-1}A^TA)^T = (AA^T)^{-1}(A^TA)^T = (AA^T)^{-1}A^TA = A^TA$.

---

4. Let $\mathcal{P}^n$ be the real vector space of order $n$ polynomials of the form $p(x) = \sum_{i=0}^n \alpha_i x^i$. Verify that the following is a scalar product over $\mathcal{P}^n$ : $\langle p_1, p_2\rangle = \int_{-1}^{+1} dx \, p_1(x) p_2(x)$.

The integral satisfies all required properties. The only non-trivial one is the norm. For any $x^k$, you have $\langle x^k, x^k\rangle = \int_{-1}^{+1} dx \, x^{2k} = \frac{1}{2k+1}(1^{2k+1} - (-1)^{2k+1}) = \frac{2}{2k+1}$.

When computing the $\langle x^k, x^m \rangle$, there are 2 cases: if $k+m$ is even, then $\langle x^k, x^m \rangle = \frac{2}{m + k + 1}$. If $k+m$ is odd, the result is 0. 

If you compute $\langle p, p\rangle$ for any polynomial, this is equivalent to computing $\int_{-1}^{+1} dx \, p^2(x)$.

$p^2(x)$ is always positive, therefore $\langle p, p\rangle\geq 0$.

Suppose there exist a non-zero polynomial $p$ s.t. $\langle p, p\rangle = 0$. There exists $x_0\in[-1, 1]$ s.t. $p(x_0)>0$. Polynomials are continuous functions, therefore there exist an interval $[a,b]\subseteq[-1,1]$ on which $p(x)>\frac{1}{2}p(x_0)$

Therefore $\langle p, p\rangle\geq\int_a^b dx \, p^2(x)>\frac{1}{4}p(x_0)^2(b-a)>0$, hence $\langle p, p\rangle\ = 0\Rightarrow p=0$.

---

5. Using this scalar product and the Gram-Schmidt orthogonalization process, compute an orthonogonal basis of $\mathcal{P}^n$. (these are the celebrated Legendre polynomials).
Compute the first 4 orthogonal basis vectors using Gram-Schmidt process. By convention, the Legendre polynomials are scaled s.t. $p(1)=1$.

- $u_0 = v_0 = 1$

- $v_1 = x, u_1 = v_1 - P_{u_0}v_1 = x - \frac{\langle x, 1\rangle}{\langle 1, 1\rangle}1$.

But $\langle x, 1\rangle = \int_{-1}^{+1} dx \, x = 0$, hence $u_1 = x$.

- $v_2 = x^2, u_2 = v_2 - P_{u_1}v_2 - P_{u_0}v_2 = x^2 - \frac{\langle x^2, x\rangle}{\langle x, x\rangle}x  - \frac{\langle x^2, 1\rangle}{\langle 1, 1\rangle}1$

From the previous question $\langle 1, 1\rangle = 2$ and $\langle x, x\rangle = 2/3$. After integration $\langle x^2, 1\rangle = 2/3$ and $\langle x^2, x\rangle = 0$, which leads to $u_2 = x^2 -\frac{1}{3}$. If we force its value at 1 to be 1, we have $u_2 = \frac{1}{2}(3x^2 - 1)$.

- $v_3 = x^3, u_3= v_3 - P_{u_2}v_3 - P_{u_1}v_3 - P_{u_0}v_3$

$P_{u_0}v_3 = 0$, $P_{u_1}v3 = \frac{\langle x^3, x\rangle}{\langle x, x\rangle}x = \frac{3}{5}x$

$P_{u_2}v_3 = \frac{\langle x^3, u_2\rangle}{\langle u_2, u_2\rangle}$

$\langle u2, u2 \rangle = 2/5$, but $\langle x^3, u_2\rangle$ = 0. Therefore:

$u_3 = x^3 - \frac{3}{5}x$. If we force its value at 1 to be 1, we obtain $u_3 = \frac{1}{2}(5x^3 - 3x)$.


The matrix of the Legendre coefs is then

$L=\begin{pmatrix}
1 & 0 & -\frac{1}{2} & 0\\
0 & 1 & 0 &  -\frac{3}{2}\\
0 & 0 & \frac{3}{2} & 0\\
0 & 0 & 0 & \frac{5}{2}
\end{pmatrix}$

---

6. Let $D: \mathcal{P}^n \rightarrow \mathcal{P}^{n-1}$ be the linear application defined by the derivative $D(p(x)) = p'(x)$. Compute the matrix representation of $D$ using an orthogonal basis of $\mathcal{P}^n$ and $\mathcal{P}^{n-1}$. Is $D$ onto ? Is D 1-1?

The matrix $D$ for the canonical basis (keeping degree max = 3) is

$D=\begin{pmatrix}
0 & 1 & 0 & 0\\
0 & 0 & 2 & 0\\
0 & 0 & 0 & 3\end{pmatrix}$

In the Legendre basis the derivative matrix is

$D_L = \begin{pmatrix}
0 & 1 & 0 & 1\\
0 & 0 & 3 & 0\\
0 & 0 & 0 & 5\end{pmatrix}$

The derivative of $u_0$ and $u_1$ are trivial, derivative of $u_2$ is $3x = 3u_1$. 

Derivative of $u_3$  is $\frac{1}{2}(15x^2-3) = 5u_2 + u_0$.

$D$ and $D_L$ are onto since every polynomial is integrable (hence its antecedent exists), but not 1-1 since two polynomials differing by only the constant term will have the same derivative.
This is also clear from the matrix, as the first column is 0 and the 3 others are clearly independent, the rank of $D$ and $D_L$ is 3, meaning the matrix is onto.

We can also solve this using the matrix $L$. The columns vectors $u_k$ of $L$ are the coordinates of the Legendre basis vectors expressed in the canonical basis. A polynomial expressed in the Legendre basis as $p(x) = \sum_{k=0}^{n-1}a_ku_k(x)$, each $u_k(x)$ being a polynomial, expressed in the canonical basis, i.e. $u_k(x)=\sum_{m=0}^{n-1}u_{km}x^m$. Replacing in the previous definition, we then have: $p(x) = \sum_{k=0}^{n-1}a_k\sum_{m=0}^{n-1}u_{km}x^m=\sum_{m=0}^{n-1}\sum_{k=0}^{n-1}a_ku_{km}x^k = \sum_{k=0}^{n-11}b_kx^k$.

We can rewrite this as a matrix operation $\begin{pmatrix}b_0\\b_1\\ \vdots\\b_{n-1}\end{pmatrix} = L\begin{pmatrix}a_0\\a_1\\ \vdots\\a_{n-1}\end{pmatrix}$

Given a polynomial in the canonical basis, its coefficients in the Legendre basis would be $a=L^{-1}b$. In our case $L^1$ can be computed by hand (or via `np.linalg.inv`). We have:

$L^{-1}=\begin{pmatrix}
1 & 0 & \frac{1}{3} & 0\\
0 & 1 & 0 &  \frac{3}{5}\\
0 & 0 & \frac{2}{3} & 0\\
0 & 0 & 0 & \frac{2}{5}
\end{pmatrix}$

If we use a slighlty different definition for $D$, s.t. it is no longer $D: \mathcal{P}^n \rightarrow \mathcal{P}^{n-1}$ but $D_s: \mathcal{P}^n \rightarrow \mathcal{P}^{n}$, its matrix will be squared and we have

$D_s=\begin{pmatrix}
0 & 1 & 0 & 0\\
0 & 0 & 2 & 0\\
0 & 0 & 0 & 3 \\
0 & 0 & 0 & 0 \end{pmatrix}$


Applying the operator $D$ to a polynomial (represented as a vector) expressed in the Legendre basis $p_L$ can be done by first expressing converting it to the canonical basis, apply the operator then back to Legendre, i.e.

$D_Lp_L = L^{-1}DLp_L$, meaning $D_L = L^{-1}DL$.

---

In [1]:
import numpy as np

In [20]:
D = np.array([[0, 1, 0, 0], [0, 0, 2, 0], [0, 0, 0, 3]])

Simple numerical example: $p(x) = x + x^2$, canonical basis

In [2]:
p = np.array([0, 1, 1, 0])

In [31]:
D@p

array([1, 2, 0])

As expected, derivative of $p$ is $1 +2x$. 

In the Legendre basis, $p = \frac{2}{3}u_2 + u_1 + \frac{1}{3}u_0$.

In [32]:
pL = np.array([1/3, 1, 2/3, 0])

In [35]:
DL = np.array([[0, 1, 0, 1], [0, 0, 3, 0], [0, 0, 0, 5]])

In [36]:
DL@pL

array([1., 2., 0.])

In the Legendre basis, derivative of $p$ is $u_0 + 2u_1 = 1 + 2x$.

We can achieve the same results using $L$ and its inverse:

In [23]:
L = np.array([[1, 0, -0.5, 0], [0, 1, 0, -1.5], [0, 0, 1.5, 0], [0, 0, 0, 2.5]])

In [25]:
np.linalg.inv(L)

array([[1.        , 0.        , 0.33333333, 0.        ],
       [0.        , 1.        , 0.        , 0.6       ],
       [0.        , 0.        , 0.66666667, 0.        ],
       [0.        , 0.        , 0.        , 0.4       ]])

In [26]:
pL = np.linalg.inv(L)@p

In [27]:
pL

array([0.33333333, 1.        , 0.66666667, 0.        ])

In [28]:
D@p

array([1, 2, 0])

In [32]:
Dsquare = np.zeros((4,4))
Dsquare[:3 ,:] = D
Dsquare

array([[0., 1., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 3.],
       [0., 0., 0., 0.]])

In [38]:
DsquareL = np.linalg.inv(L)@Dsquare@L
DsquareL

array([[0., 1., 0., 1.],
       [0., 0., 3., 0.],
       [0., 0., 0., 5.],
       [0., 0., 0., 0.]])

In [39]:
DsquareL@pL

array([1., 2., 0., 0.])